name: Build V2Ray rules dat files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Checkout to "build" branch
        uses: actions/checkout@v3
        with:
          ref: build

      - name: Run build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdir -p ./publish
          python main.py

      - name: Set variables
        run: |
          # ref https://github.com/Loyalsoldier/v2ray-rules-dat/blob/master/.github/workflows/run.yml
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy files to tmp folder
        run: |
          mkdir /tmp/rules
          cp ./publish/* /tmp/rules

      - name: Checkout to "build" branch
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Delete original files
        run: |
          rm -rf *
          cp /tmp/rules/* .

      - name: Git push assets to "release" branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change ${{ env.COMMIT_DATE }}
          branch: release

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Update profiles on running instance
        run: |
          if [ ${{ env.GIT_BRANCH_NAME }} == 'main' ]
          then
            curl -XPOST -H "Authorization: Token ${{ secrets.SBC_INSTANCE_TOKEN }}" -H "Content-Type: application/json" ${{ secrets.SBC_INSTANCE_URL }}/api/v1/update-all-profiles
          fi
